nombres_1 = [
    "Agustin",
    "Alan",
    "Andrés",
    "Ariadna",
    "Bautista",
    "CAROLINA",
    "CESAR",
    "David",
    "Diego",
    "Dolores",
    "DYLAN",
    "ELIANA",
    "Emanuel",
    "Fabián",
    "Facundo",
    "Facundo",
    "FEDERICO",
    "FEDERICO",
    "GONZALO",
    "Gregorio",
    "Ignacio",
    "Jonathan",
    "Jonathan",
    "Jorge",
    "JOSE",
    "JUAN",
    "Juan",
    "Juan",
    "Julian",
    "Julieta",
    "LAUTARO",
    "Leonel",
    "LUIS",
    "Luis",
    "Marcos",
    "María",
    "MATEO",
    "Matias",
    "Nicolás",
    "NICOLÁS",
    "Noelia",
    "Pablo",
    "Priscila",
    "TOMAS",
    "Tomás",
    "Ulises",
    "Yanina",
]
nombres_2 = [
    "Agustin",
    "AGUSTIN",
    "Agustín",
    "Ailen",
    "Alfredo",
    "Amalia",
    "Ariana",
    "Bautista",
    "Braian",
    "Carla",
    "CESAR",
    "Daniel",
    "Diego",
    "ELIANA",
    "Facundo",
    "Facundo",
    "Facundo",
    "Facundo",
    "Federico",
    "Federico",
    "Flavia",
    "Francisco",
    "Germán",
    "Guido",
    "GUSTAVO",
    "Hilario",
    "Ignacio",
    "IVAN",
    "Jimmy",
    "Joaquín",
    "Jose",
    "Josue",
    "JUAN",
    "Juan",
    "Laura",
    "LAURA",
    "Lautaro",
    "Lautaro",
    "Ludmila",
    "Marcos",
    "Marcos",
    "MARIANELA",
    "MARTIN",
    "MATEO",
    "Mateo",
    "Matias",
    "MAURO",
    "Maximiliano",
    "NESTOR",
    "Nicolas",
    "Pedro",
    "Ramiro",
    "Sofía",
    "Tobias",
    "Tomás",
    "Tomás",
    "Ulises",
    "Yanina",
]
eval_1 = [
    81,
    60,
    72,
    24,
    15,
    91,
    12,
    70,
    29,
    42,
    16,
    3,
    35,
    67,
    10,
    57,
    11,
    69,
    12,
    77,
    13,
    86,
    48,
    65,
    51,
    41,
    87,
    43,
    10,
    87,
    91,
    15,
    44,
    85,
    73,
    37,
    42,
    95,
    18,
    7,
    74,
    60,
    9,
    65,
    93,
    63,
    74,
]
eval_2 = [
    30,
    95,
    28,
    84,
    84,
    43,
    66,
    51,
    4,
    11,
    58,
    10,
    13,
    34,
    96,
    71,
    86,
    37,
    64,
    13,
    8,
    87,
    14,
    14,
    49,
    27,
    55,
    69,
    77,
    59,
    57,
    40,
    96,
    24,
    30,
    73,
    95,
    19,
    47,
    15,
    31,
    39,
    15,
    74,
    33,
    57,
    10,
]

# i) Indique los nombres que se encuentran en ambos. Nota: pruebe utilizando list comprehension.
# ii) Genere dos variables con la lista de notas que se incluyen en los archivos: nombres_1, eval1.txt
# y eval2.txt e imprima con formato los nombres de los estudiantes con las correspondientes
# nota y la suma de ambas como se ve en la imagen


def imprimir_encabezado():
    print(
        "".rjust(4),
        "Nombre".ljust(15),
        "Eval1".center(10),
        "Eval2".center(10),
        "Total".center(10),
    )


def imprimir_tabla(lista_alumnos, eval1, eval2):
    """Dada una lista de alumnos y dos listas de notas,
    imprime una tabla con el nombre, la nota de cada examen
    y la nota total obtenida."""
    imprimir_encabezado()
    for i in range(len(lista_alumnos)):
        suma = eval1[i] + eval2[i]
        print(
            str(i).rjust(4),
            lista_alumnos[i].ljust(15),
            str(eval1[i]).center(10),
            str(eval2[i]).center(10),
            str(suma).center(10),
        )


def en_ambas(lista_1, lista_2):
    """Dada dos listas de alumnos, devuelve una lista con los
    nombres de alumnos que se encuentran en ambas."""
    alumnos = [alumno for alumno in lista_1 if alumno in lista_2]
    return alumnos


print(f"Alumnos que están en ambas listas: \n{en_ambas(nombres_1, nombres_2)}")
imprimir_tabla(nombres_1, eval_1, eval_2)